POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Elämäni ja koirat",
    "author": "Samuelin veli",
    "url": "www.vihreä-koira-ja-parta.fi",
    "likes": "7"
}


